# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4baa67a89417d57b9cf469aadf3ca6618db332ebb0693e6d4ba4d8abe8b774bbce133283db00fd1bac369945f8c160fa2f849aeb0d280c7f61680285171c28d9

test:
  secret_key_base: 25cc5ec83959172401059fb9a3deea81ad7fef4bfa7f41966cc3731a9a2cc7ff43fbc89755725c07be191311099aa3012e242d57baa9931931b226701c623e6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
